FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000                                          # ✅ changed 3000 → 5000

CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]  # ✅ changed 3000 → 5000
